import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sub Post Page",
  description: "Generated by Post Page",
};

export default async function page({ params }: { params: { id: string } }) {
  const { id } = params
  return (
    <>
      <h1>Sub Post {id}</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo eligendi officiis, libero cum dicta ducimus illum tenetur perspiciatis natus neque nesciunt tempora optio quo est porro voluptatibus, suscipit, non dolorem?</p>
    </>
  )
}
